### ISSUE TITLE
Predicate exception

### ISSUE THREAD

**Issue by b4435242** [Joshua27/ProBramSynthesis#1]
Hi, 

I tried to reproduce the project and yet encountered the error while executing `synthesizer.synthesizePredicate(positiveExamples, negativeExamples);` Could you kindly give me some hints to solve this issue? Thanks.

![Screenshot from 2022-11-14 20-14-15](https://user-images.githubusercontent.com/49785533/201657660-c220cd4d-b6b7-4d01-b7b7-a4d0f18eddc5.png)

**Comment by Joshua27** [comment]
Hi,
thank you for reporting the issue and sorry for the inconvenience.
It works again now.
